blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('blog_app.urls')),
    url(r'^admin/', admin.site.urls),
]

blog_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^article/$', views.article, name='article'),
    url(r'^tag/$', views.tag, name='tag'),
    url(r'^archive/$', views.archive, name='archive'),
    url(r'^test/$', views.test, name='test'),
    url(r'^about/$', views.about, name='about')
]

blog_app/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    avatar = models.ImageField('头像', upload_to='avatar/%Y/%m', \
                                default='avatar/default.png', max_length=200, blank=True, null=True)
    url = models.URLField(max_length=100, blank=True, null=True, verbose_name='个人网页地址')

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username


# Create your models here.
class Tag(models.Model):
    name = models.CharField('标签名称', max_length=30)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField('分类', max_length=30)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class ArticleManager(models.Manager):
    def distinct_date(self):
        distinct_date_list = []
        date_list = self.values('date_publish')
        for date in date_list:
            date = date['date_publish'].strftime('%Y /%m 文章存档')
            if date not in distinct_date_list:
                distinct_date_list.append(date)
        return distinct_date_list


class Article(models.Model):
    title = models.CharField('文章标题', max_length=50)
    desc = models.CharField('文章描述', max_length=50)
    content = models.TextField('文章内容')
    click_count = models.IntegerField('点击次数', default=0)
    is_recommend = models.BooleanField('是否推荐', default=False)
    date_publish = models.DateTimeField('发布时间', auto_now_add=True)
    user = models.ForeignKey(User, verbose_name='作者')
    category = models.ForeignKey(Category, blank=True, null=True, verbose_name='分类')
    tag = models.ManyToManyField(Tag, verbose_name='标签')

    objects = ArticleManager()

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField('评论内容')
    username = models.CharField('用户名', max_length=30, blank=True, null=True)
    email = models.EmailField('邮箱地址', max_length=50, blank=True, null=True)
    url = models.URLField('个人网址', max_length=100, blank=True, null=True)
    date_publish = models.DateTimeField('发布时间', auto_now_add=True)
    user = models.ForeignKey(User, blank=True, null=True, verbose_name='用户')
    article = models.ForeignKey(Article, blank=True, null=True, verbose_name='文章')
    pid = models.ForeignKey('self', blank=True, null=True, verbose_name='文章')

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.id)

blog_app/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.conf import settings
from django.db.models import Q
from .models import User
import re


class LoginForm(forms.Form):
    '''
    登录Form
    '''
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username", "required": "required",}),
                              max_length=50,error_messages={"required": "username不能为空",})
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password", "required": "required",}),
                              max_length=20,error_messages={"required": "password不能为空",})


class RegForm(forms.Form):
    '''
    注册表单
    '''
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username", "required": "required",}),
                              max_length=50,error_messages={"required": "username不能为空",})
    email = forms.EmailField(widget=forms.TextInput(attrs={"placeholder": "Email", "required": "required",}),
                              max_length=50,error_messages={"required": "email不能为空",})
    url = forms.URLField(widget=forms.TextInput(attrs={"placeholder": "Url", }),
                              max_length=100, required=False)
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password", "required": "required",}),
                              max_length=20,error_messages={"required": "password不能为空",})


class CommentForm(forms.Form):
    '''
    评论表单
    '''
    author = forms.CharField(widget=forms.TextInput(attrs={"id": "author", "class": "comment_input",
                                                           "required": "required","size": "25", "tabindex": "1"}),
                              max_length=50,error_messages={"required":"username不能为空",})
    email = forms.EmailField(widget=forms.TextInput(attrs={"id":"email","type":"email","class": "comment_input",
                                                           "required":"required","size":"25", "tabindex":"2"}),
                                 max_length=50, error_messages={"required":"email不能为空",})
    url = forms.URLField(widget=forms.TextInput(attrs={"id":"url","type":"url","class": "comment_input",
                                                       "size":"25", "tabindex":"3"}),
                              max_length=100, required=False)
    comment = forms.CharField(widget=forms.Textarea(attrs={"id":"comment","class": "message_input",
                                                           "required": "required", "cols": "25",
                                                           "rows": "5", "tabindex": "4"}),
                                                    error_messages={"required":"评论不能为空",})
    article = forms.CharField(widget=forms.HiddenInput())

blog_app/views.py
import logging
from django.shortcuts import render
from django.conf import settings
from .models import *
from .forms import *


# 日志的使用
logger = logging.getLogger('blog_app.views')
# try:
#     pass
# except Exception as e:
#     logger.error(e)


def global_setting(request):
    return {
            'SITE_NAME': settings.SITE_NAME,
    }


def index(request):
    article_list = Article.objects.all()
    return render(request, 'index.html', locals())


def article(request):
    try:
        # 获取文章id
        id = request.GET.get('id', None)
        try:
            # 获取文章信息
            article = Article.objects.get(pk=id)
        except Article.DoesNotExist:
            return render(request, '404.html', {'reason': '没有找到对应的文章'})

        # 评论表单
        comment_form = CommentForm({'author': request.user.username,
                                    'email': request.user.email,
                                    'url': request.user.url,
                                    'article': id} if request.user.is_authenticated() else{'article': id})
        # 获取评论信息
        comments = Comment.objects.filter(article=article).order_by('id')
        comment_list = []
        for comment in comments:
            for item in comment_list:
                if not hasattr(item, 'children_comment'):
                    setattr(item, 'children_comment', [])
                if comment.pid == item:
                    item.children_comment.append(comment)
                    break
            if comment.pid is None:
                comment_list.append(comment)
    except Exception as e:
        print(e)
        logger.error(e)
    return render(request, 'article.html', locals())


def tag(request):
    tag_list = Tag.objects.all()
    return render(request, 'tag.html', locals())


def archive(request):
    try:
        # year = request.GET.get('year', None)
        # month = request.GET.get('month', None)
        # article_list = Article.objects.filter(date_publish__contains=year+'-'+month)
        # article_list = getPage(request, article_list)
        article_list = Article.objects.all()
    except Exception as e:
        logger.error(e)
    return render(request, 'archive.html', locals())

def about(request):
    return render(request, 'about.html')


def test(request):
    print(locals())
    return render(request, 'test.html', locals())

blog_app/templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div id="about-banner" style="background-image: url({% static '/css/images/about.jpg' %})"></div>
    <div class="author">
        <div class="head">
            <img src="{% static '/css/images/logo.png' %}" />
        </div>
        <h3>hukx.michael</h3>
        <p class="discription">Life is so beautiful</p>
        <section class="share-icons">
            <a class="icon-twitter" href="https://twitter.com/hukx_michael" target="_blank">
                <span class="fa-stack fa-lg">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
        </span>
            </a>
            <a class="icon-github" href="https://github.com/hukaixuan" target="_blank">
                <span class="fa-stack fa-lg">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-github fa-stack-1x fa-inverse"></i>
        </span>
            </a>
            <a class="icon-zhihu" href="https://www.zhihu.com/people/hukx.michael" target="_blank">
                <span class="fa-stack fa-lg">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-stack-1x fa-inverse">知</i>
        </span>
            </a>
        </section>
    </div>
{% endblock %}

{% block script %}
    <script>
    (function() {
        $('.header').removeClass('fixed-header')
        var windowH = $(window).height();
        var author = $('.author')
        var bodyH = author.offset().top + author[0].offsetHeight + 71;
        if (bodyH < windowH) {
            author.css({
                'margin-bottom': windowH - bodyH
            })
        }
    })();
    </script>
    <div class="scroll-top">
        <span class="arrow-icon"></span>
    </div>
    <script>
    function async(u, c) {
        var d = document,
            t = 'script',
            o = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
        o.src = u;
        if (c) {
            o.addEventListener('load', function(e) {
                c(null, e);
            }, false);
        }
        s.parentNode.insertBefore(o, s);
    }
    </script>
    <script>
    async("//cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js", function() {
        FastClick.attach(document.body);
    })
    </script>
    <script>
    var hasLine = 'true';
    async("//cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js", function() {
        $('figure pre').each(function(i, block) {
            var figure = $(this).parents('figure');
            if (hasLine == 'false') {
                figure.find('.gutter').hide();
            }
            var lang = figure.attr('class').split(' ')[1] || 'code';
            var codeHtml = $(this).html();
            var codeTag = document.createElement('code');
            codeTag.className = lang;
            codeTag.innerHTML = codeHtml;
            $(this).attr('class', '').empty().html(codeTag);
            figure.attr('data-lang', lang.toUpperCase());
            hljs.highlightBlock(block);
        });
    })
    </script>
    <!-- Baidu Tongji -->
    <script src="{% static '/js/script.js' %}"></script>
{% endblock %}

blog_app/templates/archive.html
{% extends 'base.html' %} 
{% load staticfiles %}


{% block content %}
<div id="article-banner">
    <h2>Archives</h2>
    <p class="post-date">文章归档</p>
</div>
<main class="app-body" id="archives">
    <section class="time-section">
        <h1 class="section-year">
            2017
  </h1>
        <div class="section-list">
            {% for article in article_list %}
                <div class="section-list-item">
                    <a href="/2017/06/30/项目演示--基于地理位置的社交系统/" class="archive-title">{{ article.title }}</a>
                    <p class="archive-date">{{ article.date_publish }}</p>
                </div>
            {% endfor %}

        </div>
    </section>
</main>

{% endblock %}

{% block script %}
<script>
(function() {
    var url = {% url 'article' %}+'?id={{ article.id }}';
    $('#article-banner').geopattern(url);
    $('.header').removeClass('fixed-header');
})();
</script>
<div class="scroll-top">
    <span class="arrow-icon"></span>
</div>
<script>
function async(u, c) {
    var d = document,
        t = 'script',
        o = d.createElement(t),
        s = d.getElementsByTagName(t)[0];
    o.src = u;
    if (c) {
        o.addEventListener('load', function(e) {
            c(null, e);
        }, false);
    }
    s.parentNode.insertBefore(o, s);
}
</script>
<script>
async("//cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js", function() {
    FastClick.attach(document.body);
})
</script>
<script>
var hasLine = 'true';
async("//cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js", function() {
    $('figure pre').each(function(i, block) {
        var figure = $(this).parents('figure');
        if (hasLine == 'false') {
            figure.find('.gutter').hide();
        }
        var lang = figure.attr('class').split(' ')[1] || 'code';
        var codeHtml = $(this).html();
        var codeTag = document.createElement('code');
        codeTag.className = lang;
        codeTag.innerHTML = codeHtml;
        $(this).attr('class', '').empty().html(codeTag);
        figure.attr('data-lang', lang.toUpperCase());
        hljs.highlightBlock(block);
    });
})
</script>
<!-- Baidu Tongji -->
<script src="{% static '/js/script.js' %}"></script>
{% endblock %}

blog_app/templates/article.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <div id="article-banner">
        <h2>{{ article.title }}</h2>
        <p class="post-date">2017-04-10</p>
        <div class="arrow-down">
            <a href="javascript:;"></a>
        </div>
    </div>
    <main class="app-body">
        <article class="post-article">
            <section class="markdown-content">
                {{ article.content }}
            </section>
            <div class="tags">
                <span>Tags:</span>
                {% for tag in article.tag.all %}
                    <span class="tag-code">{{ tag }}</span>
                {% endfor %}

            </div>
            <div class="money-like">
                <div class="reward-btn">
                    赏
                    <span class="money-code">
          <span class="alipay-code">
            <div class="code-image"></div>
            <b>使用支付宝打赏</b>
          </span>
                    <span class="wechat-code">
            <div class="code-image"></div>
            <b>使用微信打赏</b>
          </span>
                    </span>
                </div>
                <p class="notice">若你觉得我的文章对你有帮助，欢迎点击上方按钮对我打赏</p>
            </div>
            <div class="qrcode">
                <canvas id="share-qrcode"></canvas>
                <p class="notice">扫描二维码，分享此文章</p>
            </div>
            <div id="comments"></div>
        </article>
    </main>
{% endblock %}

{% block script %}
<script>
    (function() {
        var url = {% url 'article' %}+'?id={{ article.id }}';
        $('#article-banner').geopattern(url)
        $('.header').removeClass('fixed-header')

        // error image
        $(".markdown-content img").on('error', function() {
            $(this).attr('src', 'http://yanm1ng.cn/error-img.png')
        })

        // zoom image
        $(".markdown-content img").on('click', function() {
            var src = $(this).attr('src')
            var imageW = $(this).width()
            var imageH = $(this).height()

            var zoom = ($(window).width() * 0.95 / imageW).toFixed(2)
            zoom = zoom < 1 ? 1 : zoom
            zoom = zoom > 2 ? 2 : zoom
            var transY = (($(window).height() - imageH) / 2).toFixed(2)

            $('body').append('<div class="image-view-wrap"><div class="image-view-inner"><img src="' + src + '" /></div></div>')
            $('.image-view-wrap').addClass('wrap-active')
            $('.image-view-wrap img').css({
                'width': `${imageW}`,
                'transform': `translate3d(0, ${transY}px, 0) scale3d(${zoom}, ${zoom}, 1)`
            })
            $('html').css('overflow', 'hidden')

            $('.image-view-wrap').on('click', function() {
                $(this).remove()
                $('html').attr('style', '')
            })
        })

        // qrcode
        var qr = new QRious({
            element: document.getElementById('share-qrcode'),
            value: document.location.href
        });

        // gitment
        var gitmentConfig = "hukaixuan";
        if (gitmentConfig != "undefined") {
            var gitment = new Gitment({
                owner: "hukaixuan",
                repo: "hukaixuan.github.io",
                oauth: {
                    client_id: "057dbc7c9172e901c3bb",
                    client_secret: "8a90a976396137e6ac92922a4680dcb8c8130cfb"
                },
                theme: {
                    render(state, instance) {
                        const container = document.createElement('div')
                        container.lang = "en-US"
                        container.className = 'gitment-container gitment-root-container'
                        container.appendChild(instance.renderHeader(state, instance))
                        container.appendChild(instance.renderEditor(state, instance))
                        container.appendChild(instance.renderComments(state, instance))
                        container.appendChild(instance.renderFooter(state, instance))
                        return container;
                    }
                }
            })
            gitment.render(document.getElementById('comments'))
        }
    })();
    </script>
    <div class="scroll-top">
        <span class="arrow-icon"></span>
    </div>
    <script>
    function async(u, c) {
        var d = document,
            t = 'script',
            o = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
        o.src = u;
        if (c) {
            o.addEventListener('load', function(e) {
                c(null, e);
            }, false);
        }
        s.parentNode.insertBefore(o, s);
    }
    </script>
    <script>
    async("//cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js", function() {
        FastClick.attach(document.body);
    })
    </script>
    <script>
    var hasLine = 'true';
    async("//cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js", function() {
        $('figure pre').each(function(i, block) {
            var figure = $(this).parents('figure');
            if (hasLine == 'false') {
                figure.find('.gutter').hide();
            }
            var lang = figure.attr('class').split(' ')[1] || 'code';
            var codeHtml = $(this).html();
            var codeTag = document.createElement('code');
            codeTag.className = lang;
            codeTag.innerHTML = codeHtml;
            $(this).attr('class', '').empty().html(codeTag);
            figure.attr('data-lang', lang.toUpperCase());
            hljs.highlightBlock(block);
        });
    })
    </script>
    <!-- Baidu Tongji -->
    <script src="{% static '/js/script.js' %}"></script>
{% endblock %}

blog_app/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
    <meta name="description" content="The blog of hukx.michael">
    <meta name="keyword" content="hexo-theme, vuejs">
    <title>
        {{ SITE_NAME }}
    </title>
    <link href="//cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/nprogress/0.2.0/nprogress.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/highlight.js/9.12.0/styles/tomorrow.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" href="{% static '/css/plugins/gitment.css' %}">
    <script src="//cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/geopattern/1.2.3/js/geopattern.min.js"></script>
    <script src="//cdn.bootcss.com/nprogress/0.2.0/nprogress.min.js"></script>
    <script src="{% static '/js/qrious.js' %}"></script>
    <script src="{% static '/js/gitment.js' %}"></script>
</head>

<body>
    <header class="header fixed-header">
        <div class="header-container">
            <a class="home-link" href="/">
                <div class="logo"></div>
                <span>{{ SITE_NAME }}</span>
            </a>
            <ul class="right-list">
                <li class="list-item">
                    <a href="/" class="item-link">Home</a>
                </li>
                <li class="list-item">
                    <a href="{% url 'tag' %}" class="item-link">Tags</a>
                </li>
                <li class="list-item">
                    <a href="{% url 'archive' %}" class="item-link">Archives</a>
                </li>
                <li class="list-item">
                    <a href="{% url 'about' %}" class="item-link">About</a>
                </li>
            </ul>
            <div class="menu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </div>
            <div class="menu-mask">
                <ul class="menu-list">
                    <li class="menu-item">
                        <a href="/" class="menu-link mobile-active">Home</a>
                    </li>
                    <li class="menu-item">
                        <a href="{% url 'tag' %}" class="menu-link">Tags</a>
                    </li>
                    <li class="menu-item">
                        <a href="{% url 'archive' %}" class="menu-link">Archives</a>
                    </li>
                    <li class="menu-item">
                        <a href="{% url 'about' %}" class="menu-link">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    {% block content %}

    {% endblock %}
    <footer class="app-footer">
        <p class="copyright">
            &copy; create by <a href="https://github.com/hukaixuan">hukaixuan</a>
        </p>
    </footer>

    {% block script %}
    {% endblock %}
</body>

</html>

blog_app/templates/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <main class="app-body">
        {% for article in article_list %}
            <article class="article-card">
                <h2 class="article-head">
                    <a href="{% url 'article' %}?id={{ article.id }}">{{ article.title }}</a>
                </h2>
                <p class="article-date">{{ article.date_publish }}</p>
                {% for tag in article.tag.all %}
                    <span class="tag-code">{{ tag }}</span>
                {% endfor %}
                <div class="article-summary">
                    {{ article.content }}
                </div>
                <a class="more" href="{% url 'article' %}?id={{ article.id }}">Read more</a>
            </article>
        {% endfor %}

        </main>
    <div class="guide-pager">
        <a class="unvisible" href="/"><span class="page-arrow">←</span> Prev</a>
        <a href="/page/2/">Next<span class="page-arrow"> →</span></a>
    </div>
    <div class="scroll-top">
            <span class="arrow-icon"></span>
        </div>
{% endblock %}

{% block script %}
<script>
    function async(u, c) {
        var d = document,
            t = 'script',
            o = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
        o.src = u;
        if (c) {
            o.addEventListener('load', function(e) {
                c(null, e);
            }, false);
        }
        s.parentNode.insertBefore(o, s);
    }
    </script>
    <script>
    async("//cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js", function() {
        FastClick.attach(document.body);
    })
    </script>
    <script>
    var hasLine = 'true';
    async("//cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js", function() {
        $('figure pre').each(function(i, block) {
            var figure = $(this).parents('figure');
            if (hasLine == 'false') {
                figure.find('.gutter').hide();
            }
            var lang = figure.attr('class').split(' ')[1] || 'code';
            var codeHtml = $(this).html();
            var codeTag = document.createElement('code');
            codeTag.className = lang;
            codeTag.innerHTML = codeHtml;
            $(this).attr('class', '').empty().html(codeTag);
            figure.attr('data-lang', lang.toUpperCase());
            hljs.highlightBlock(block);
        });
    })
    </script>
    <!-- Baidu Tongji -->
    <script src="{% static '/js/script.js' %}"></script>
{% endblock %}

blog_app/templates/tag.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
<div id="article-banner">
        <h2>Tags</h2>
        <p class="post-date">标签检索</p>
    </div>
    <main class="app-body">
        <div id="tag-cloud">
            {% for tag in tag_list %}
                <a class="tag" data-name="tag-{{ tag.id }}">{{ tag.name }}</a>
            {% endfor %}

{#            <a class="tag2" data-name="tag-1">Flask</a>#}
{#            <a class="tag3" data-name="tag-2">MySQL</a>#}
{#            <a class="tag2" data-name="tag-3">git</a>#}
{#            <a class="tag0" data-name="tag-4">Nginx</a>#}
{#            <a class="tag3" data-name="tag-5">HTTPS</a>#}
{#            <a class="tag2" data-name="tag-6">RESTful</a>#}
{#            <a class="tag2" data-name="tag-7">Linux</a>#}
{#            <a class="tag2" data-name="tag-8">Mac</a>#}
{#            <a class="tag3" data-name="tag-9">Redis</a>#}
{#            <a class="tag2" data-name="tag-10">项目展示</a>#}
{#            <a class="tag2" data-name="tag-11">爬虫</a>#}
        </div>
            {% for tag in tag_list %}
                <div class="tag-list">
                    <h3 class="tag-name" id="tag-{{ tag.id }}">{{ tag.name }}</h3>
                    {% for article in tag.article_set.all %}
                        <ul class="tag-preview">
                            <li>
                                <a href="{% url 'article' %}?id={{ article.id }}">{{ article.title }}</a>
                            </li>
                        </ul>
                    {% endfor %}
                </div>
            {% endfor %}
    </main>
{% endblock %}

{% block script %}
<script>
    (function() {
        var url = '{% url 'index' %}'+Math.random();
        $('#article-banner').geopattern(url);
        $('.header').removeClass('fixed-header')
    })();
    </script>
    <div class="scroll-top">
        <span class="arrow-icon"></span>
    </div>
    <script>
    function async(u, c) {
        var d = document,
            t = 'script',
            o = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
        o.src = u;
        if (c) {
            o.addEventListener('load', function(e) {
                c(null, e);
            }, false);
        }
        s.parentNode.insertBefore(o, s);
    }
    </script>
    <script>
    async("//cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js", function() {
        FastClick.attach(document.body);
    })
    </script>
    <script>
    var hasLine = 'true';
    async("//cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js", function() {
        $('figure pre').each(function(i, block) {
            var figure = $(this).parents('figure');
            if (hasLine == 'false') {
                figure.find('.gutter').hide();
            }
            var lang = figure.attr('class').split(' ')[1] || 'code';
            var codeHtml = $(this).html();
            var codeTag = document.createElement('code');
            codeTag.className = lang;
            codeTag.innerHTML = codeHtml;
            $(this).attr('class', '').empty().html(codeTag);
            figure.attr('data-lang', lang.toUpperCase());
            hljs.highlightBlock(block);
        });
    })
    </script>
    <!-- Baidu Tongji -->
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

blog_app/templates/test.html
hello
{{ SITE_NAME }}